"""service

Revision ID: 3448c04ea205
Revises: 81c051175ce2
Create Date: 2023-11-15 16:34:59.162993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3448c04ea205'
down_revision: Union[str, None] = '81c051175ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'updated_at')
    op.drop_column('machines', 'updated_at')
    # ### end Alembic commands ###
