"""service

Revision ID: 81c051175ce2
Revises: b78e6f70cd1b
Create Date: 2023-11-15 15:41:46.258660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81c051175ce2'
down_revision: Union[str, None] = 'b78e6f70cd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'machine_name',
               existing_type=mysql.TINYINT(),
               comment=' 1->MachineA; 2-->MachineB,3->MachineC',
               existing_comment=' 1->Admin; 2->user',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('machines', 'machine_name',
               existing_type=mysql.TINYINT(),
               comment=' 1->Admin; 2->user',
               existing_comment=' 1->MachineA; 2-->MachineB,3->MachineC',
               existing_nullable=True)
    # ### end Alembic commands ###
