"""service

Revision ID: d5754eefe213
Revises: 1b2de66f617a
Create Date: 2023-11-15 15:01:26.990644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5754eefe213'
down_revision: Union[str, None] = '1b2de66f617a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('device_type', mysql.TINYINT(display_width=1), nullable=False, comment='1-Android, 2-iOS'))
    op.add_column('api_tokens', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('api_tokens', sa.Column('push_device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_tokens', 'push_device_id')
    op.drop_column('api_tokens', 'device_id')
    op.drop_column('api_tokens', 'device_type')
    # ### end Alembic commands ###
