"""service

Revision ID: d87fbfb31002
Revises: f33ccba8b7b8
Create Date: 2023-11-15 12:11:01.334052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87fbfb31002'
down_revision: Union[str, None] = 'f33ccba8b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_time')
    # ### end Alembic commands ###
