"""service

Revision ID: e4bc4c5d0b8b
Revises: 7a574bbd73c5
Create Date: 2023-11-15 11:32:08.144729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4bc4c5d0b8b'
down_revision: Union[str, None] = '7a574bbd73c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_name', mysql.TINYINT(), nullable=True, comment=' 1->Admin; 2->user'),
    sa.Column('serial_name', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='0->inactive,1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='0->inactive,1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment=' 1->service_engineer; 2->service_technician; 3-operator; 4-> supervisor'),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=5000), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment="ForeignKey('user.id')"),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='0->inactive,1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('machines')
    # ### end Alembic commands ###
